# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
repos:
  CRAN: https://cloud.r-project.org
  Sage: https://sage-bionetworks.github.io/ran

r:
- 3.3
- oldrel
- release
- devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
